import { Sparkles, X, Brain, Target, Award, Code2 } from 'lucide-react';

export default function AISummary({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-md animate-fade-in">
      <div className="glass dark:glass-dark rounded-3xl w-full max-w-2xl shadow-2xl overflow-hidden border border-white/20 dark:border-gray-700/30 animate-fade-in-up">
        <div className="p-[clamp(1rem,2vw,1.5rem)] border-b border-white/10 flex justify-between items-center bg-gradient-to-r from-indigo-600/20 to-purple-600/20">
          <h3 className="text-xl font-[800] tracking-[-0.02em] text-gray-900 dark:text-white flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-indigo-500 animate-pulse" /> 
            AI Interview Summary
          </h3>
          <button onClick={onClose} className="p-2 hover:bg-white/10 rounded-full transition-colors">
            <X className="w-5 h-5 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-white" />
          </button>
        </div>

        <div className="p-[clamp(1rem,2vw,1.5rem)] max-h-[80vh] overflow-y-auto space-y-8">
          {/* Executive Summary */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-[800] tracking-[-0.02em] uppercase text-xs tracking-wider">
              <Brain className="w-4 h-4" /> Executive Profile
            </div>
            <p className="text-gray-700 dark:text-gray-300 leading-relaxed italic border-l-4 border-indigo-500 pl-4 py-1">
              "Kalim J is an analytics-driven Software Developer specializing in bridging the gap between complex data and functional software. With a strong foundation in Computer Science and hands-on experience in Data Analytics using Python, he is uniquely positioned to build intelligent, data-aware applications."
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Core Pillars */}
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-[800] tracking-[-0.02em] uppercase text-xs tracking-wider">
                <Target className="w-4 h-4" /> Key Strengths
              </div>
              <ul className="space-y-2">
                {['Data Analytics Lifecycle', 'End-to-End Application Dev', 'SQL Database Optimization', 'Modern Tech Stack Proficiency'].map((item, i) => (
                  <li key={i} className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
                    <div className="w-1.5 h-1.5 bg-indigo-500 rounded-full" /> {item}
                  </li>
                ))}
              </ul>
            </div>

            {/* Tech Stack Focus */}
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-[800] tracking-[-0.02em] uppercase text-xs tracking-wider">
                <Code2 className="w-4 h-4" /> Technical Focus
              </div>
              <div className="flex flex-wrap gap-2">
                {['Python', 'SQL', 'Java', 'DataViz', 'React'].map((tech) => (
                  <span key={tech} className="px-3 py-1 bg-indigo-50 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300 text-xs font-[800] tracking-[-0.02em] rounded-lg border border-indigo-100 dark:border-indigo-800">
                    {tech}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Interview Strategy */}
          <div className="p-[clamp(1rem,2vw,1.5rem)] bg-indigo-500/5 dark:bg-indigo-500/10 rounded-2xl border border-indigo-500/20">
            <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-[800] tracking-[-0.02em] uppercase text-xs tracking-wider mb-4">
              <Award className="w-4 h-4" /> Interview Talking Points
            </div>
            <div className="space-y-4 text-sm text-gray-700 dark:text-gray-300">
              <p>
                <strong>1. The "Analytical Edge":</strong> Mention your internship at Micro Infotech where you used Python for Data Analytics—it sets you apart from standard developers.
              </p>
              <p>
                <strong>2. Continuous Learner:</strong> Highlight your certifications in UI/UX, SQL, and AWS to demonstrate a self-driven learning mindset.
              </p>
              <p>
                <strong>3. Academic Foundation:</strong> Your B.E in CSE provides the structural logic needed for large-scale system design.
              </p>
            </div>
          </div>
          
          <div className="text-center text-[10px] text-gray-400 dark:text-gray-500 italic uppercase tracking-[0.2em]">
            Generated by AI Agent based on current portfolio data
          </div>
        </div>
      </div>
    </div>
  );
}
